export const SET_ID = 'SET_ID'
export const GET_SERVICES = 'GET_SERVICES'

export const UPVOTE_PARAGRAPH = 'UPVOTE_PARAGRAPH'
export const DOWNVOTE_PARAGRAPH = 'DOWNVOTE_PARAGRAPH'

export const ADD_SERVICES = 'ADD_SERVICES'
export const CLEAR_SERVICES = 'CLEAR_SERVICES'

export const FILTER_SERVICES = 'FILTER_SERVICES'
export const CLEAR_FILTER = 'CLEAR_FILTER'
