export const SET_ROUTE = 'SET_ROUTE'

export const GET_SERVICES = 'GET_SERVICES'
export const GET_PARAGRAPHS = 'GET_PARAGRAPHS'

export const UPVOTE_PARAGRAPH = 'UPVOTE_PARAGRAPH'
export const DOWNVOTE_PARAGRAPH = 'DOWNVOTE_PARAGRAPH'
export const TOGGLE_PARAGRAPH = 'TOGGLE_PARAGRAPH'

export const SET_SERVICES = 'SET_SERVICES'
export const CLEAR_SERVICES = 'CLEAR_SERVICES'

export const FILTER_SERVICES = 'FILTER_SERVICES'
export const CLEAR_FILTER = 'CLEAR_FILTER'

export const SET_PARAGRAPHS = 'SET_PARAGRAPHS'
export const CLEAR_PARAGRAPHS = 'CLEAR_PARAGRAPHS'
