const path = require('path')
const webpack = require('webpack')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const template = 'src/index.ejs'

const plugins = [
  new webpack.NoEmitOnErrorsPlugin(),
  new HtmlWebpackPlugin({
    inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
    template: template
  })
]

module.exports = require('./webpack.base.babel')({
  // Add hot reloading in development
  entry: {
    caniagree: [
      path.join(process.cwd(), 'src/index.js')
    ]
  },

  // Add development plugins
  plugins: plugins,

  // Emit a source map for easier debugging
  devtool: 'source-map'
})
